//
//  SignalGenerator.hpp
//  InvertedYieldCurveTrader
//
//  Converts macro regime classification and factor decomposition
//  into discrete trading signals for ES futures.
//
//  Created by Ryan Hamby on 1/15/26.
//

#ifndef SIGNAL_GENERATOR_HPP
#define SIGNAL_GENERATOR_HPP

#include "PositionSizer.hpp"
#include "MacroFactorModel.hpp"
#include "PortfolioRiskAnalyzer.hpp"
#include <string>
#include <vector>

enum class SignalDirection {
    LONG,
    SHORT,
    FLAT
};

/**
 * TradeSignal: Discrete trading signal from macro factor analysis
 *
 * Generated by combining regime classification, factor decomposition,
 * and market observables into an actionable direction + conviction.
 */
struct TradeSignal {
    SignalDirection direction;
    double conviction;                          // 0.0-1.0
    std::string entryReason;
    std::vector<std::string> factorsContributing;

    // Underlying data
    MacroRegime regime;
    double growthFactorScore;
    double volatilityFactorScore;
    double curveScore;
};

/**
 * SignalGenerator: Macro regime → trade signal converter
 *
 * Logic:
 *   LONG when: regime=Risk-On, growth factor positive, VIX < 20, curve steep
 *   SHORT when: regime=Risk-Off, growth factor negative, VIX > 30, curve inverted
 *   FLAT otherwise (ambiguous signals)
 *
 * Conviction = weighted average of factor signal strengths
 */
class SignalGenerator {
public:
    /**
     * Generate a trade signal from regime + factor decomposition
     *
     * @param regime: Current macro regime classification
     * @param factors: PCA factor decomposition
     * @param riskDecomp: Portfolio risk attribution
     * @return TradeSignal with direction and conviction
     */
    static TradeSignal generateSignal(
        const MacroRegime& regime,
        const MacroFactors& factors,
        const RiskDecomposition& riskDecomp
    );

    /**
     * Generate signal from raw market observables (convenience method)
     *
     * @param vixLevel: Current VIX
     * @param yieldCurveSlope: 2s10s spread in bps
     * @param growthFactorValue: Growth factor score from PCA
     * @param volatilityFactorValue: Volatility factor score from PCA
     * @param regime: Current regime classification
     * @return TradeSignal
     */
    static TradeSignal generateSignalFromObservables(
        double vixLevel,
        double yieldCurveSlope,
        double growthFactorValue,
        double volatilityFactorValue,
        const MacroRegime& regime
    );

    /**
     * Compute conviction score from factor strengths
     *
     * Weighted average of individual signal components:
     *   30% regime alignment, 25% growth factor, 20% VIX signal,
     *   15% curve signal, 10% volatility factor
     *
     * @param regimeScore: 1.0 for clear Risk-On/Off, 0.5 for Neutral
     * @param growthScore: Normalized growth factor strength [0, 1]
     * @param vixScore: Normalized VIX signal [0, 1]
     * @param curveScore: Normalized curve signal [0, 1]
     * @param volScore: Normalized volatility factor [0, 1]
     * @return Conviction [0, 1]
     */
    static double computeConviction(
        double regimeScore,
        double growthScore,
        double vixScore,
        double curveScore,
        double volScore
    );

private:
    // Signal component weights
    static constexpr double REGIME_WEIGHT = 0.30;
    static constexpr double GROWTH_WEIGHT = 0.25;
    static constexpr double VIX_SIGNAL_WEIGHT = 0.20;
    static constexpr double CURVE_SIGNAL_WEIGHT = 0.15;
    static constexpr double VOL_FACTOR_WEIGHT = 0.10;

    // Thresholds for signal generation
    static constexpr double VIX_LONG_THRESHOLD = 20.0;
    static constexpr double VIX_SHORT_THRESHOLD = 30.0;
    static constexpr double CURVE_STEEP_THRESHOLD = 50.0;    // bps
    static constexpr double CURVE_INVERTED_THRESHOLD = 0.0;  // bps
    static constexpr double MIN_CONVICTION = 0.3;            // Below this → FLAT

    /**
     * Extract growth factor value from MacroFactors
     */
    static double extractGrowthFactor(const MacroFactors& factors);

    /**
     * Extract volatility factor value from MacroFactors
     */
    static double extractVolatilityFactor(const MacroFactors& factors);
};

#endif // SIGNAL_GENERATOR_HPP
